name: LunarItems
version: '${version}'
main: me.dunescifye.lunaritems.LunarItems
description: Plugin helper for EI
api-version: '1.21'
softdepend:
  - DecentHolograms
  - GriefPrevention
  - WorldGuard
