name: LunarItems
version: '${version}'
main: me.dunescifye.lunaritems.LunarItems
description: Plugin helper for EI
softdepend:
  - DecentHolograms
  - GriefPrevention
  - WorldGuard
  - Factions
  - BaseRaiders
api-version: '1.21'
